 //pop
 export const FETCHING_NEWS = "FETCHING_NEWS";
 export const FETCHING_NEXT_PAGE_NEWS = "FETCHING_NEXT_PAGE_NEWS";
 export const ERROR_GETTING_NEWS = "ERROR_GETTING_NEWS";
 export const RECEIVED_DATA = "RECEIVED_DATA ";
 export const RECEIVED_MORE_DATA = "RECEIVED_MORE_DATA";
 //detailnews
 export const FETCHING_DETAIL_NEWS = "FETCHING_DETAIL_NEWS";
 export const RECEIVED_DETAIL_NEWS = "RECEIVED_DETAIL_NEWS";
 export const ERROR_DETAIL_NEWS = "ERROR_DETAIL_NEWS";

 //joke
 export const FETCHING_JOKE = "FETCHING_JOKE";
 export const FETCHING_NEXT_PAGE_JOKE = "FETCHING_NEXT_PAGE_JOKE";
 export const ERROR_GETTING_JOKE = "ERROR_GETTING_JOKE";
 export const RECEIVED_DATA_JOKE = "RECEIVED_DATA_JOKE ";
 export const RECEIVED_MORE_DATA_JOKE = "RECEIVED_MORE_DATA_JOKE";

 //pics
 export const FETCHING_PIC = "FETCHING_PIC";
 export const FETCHING_NEXT_PAGE_PIC = "FETCHING_NEXT_PAGE_PIC";
 export const ERROR_GETTING_PIC = "ERROR_GETTING_PIC";
 export const RECEIVED_DATA_PIC = "RECEIVED_DATA_PIC ";
 export const RECEIVED_MORE_DATA_PIC = "RECEIVED_MORE_DATA_PIC";

 //Girl

 export const FETCHING_GIRL = "FETCHING_GIRL";
 export const FETCHING_NEXT_PAGE_GIRL = "FETCHING_NEXT_PAGE_GIRL";
 export const ERROR_GETTING_GIRL = "ERROR_GETTING_GIRL";
 export const RECEIVED_DATA_GIRL = "RECEIVED_DATA_GIRL";
 export const RECEIVED_MORE_DATA_GIRL = "RECEIVED_MORE_DATA_GIRL";

 //video
 export const FETCHING_VIDEO = "FETCHING_VIDEO";
 export const FETCHING_NEXT_PAGE_VIDEO = "FETCHING_NEXT_PAGE_VIDEO";
 export const ERROR_GETTING_VIDEO = "ERROR_GETTING_VIDEO";
 export const RECEIVED_DATA_VIDEO = "RECEIVED_DATA_VIDEOL";
 export const RECEIVED_MORE_DATA_VIDEO = "RECEIVED_MORE_DATA_VIDEO";