 //pop
 export const FETCHING_NEWS = "FETCHING_NEWS";
 export const FETCHING_NEXT_PAGE_NEWS = "FETCHING_NEXT_PAGE_NEWS";
 export const ERROR_GETTING_NEWS = "ERROR_GETTING_NEWS";
 export const RECEIVED_DATA = "RECEIVED_DATA ";
 export const RECEIVED_MORE_DATA = "RECEIVED_MORE_DATA";
 //detail
 export const FETCHING_DETAIL_NEWS = "FETCHING_DETAIL_NEWS";
 export const RECEIVED_DETAIL_NEWS = "RECEIVED_DETAIL_NEWS";
 export const ERROR_DETAIL_NEWS = "ERROR_DETAIL_NEWS";

 //ask
 export const FETCHING_ASK = "FETCHING_ASK";
 export const FETCHING_NEXT_PAGE_ASK = "FETCHING_NEXT_PAGE_ASK";
 export const ERROR_GETTING_ASK = "ERROR_GETTING_ASK";
 export const RECEIVED_DATA_ASK = "RECEIVED_DATA_ASK ";
 export const RECEIVED_MORE_DATA_ASK = "RECEIVED_MORE_DATA_ASK";

 //share
 export const FETCHING_SHARE = "FETCHING_SHARE";
 export const FETCHING_NEXT_PAGE_SHARE = "FETCHING_NEXT_PAGE_SHARE";
 export const ERROR_GETTING_SHARE = "ERROR_GETTING_SHARE";
 export const RECEIVED_DATA_SHARE = "RECEIVED_DATA_SHARE ";
 export const RECEIVED_MORE_DATA_SHARE = "RECEIVED_MORE_DATA_SHARE";

 //job
 export const FETCHING_JOB = "FETCHING_JOB";
 export const FETCHING_NEXT_PAGE_JOB = "FETCHING_NEXT_PAGE_JOB";
 export const ERROR_GETTING_JOB = "ERROR_GETTING_JOB";
 export const RECEIVED_DATA_JOB = "RECEIVED_DATA_JOB";
 export const RECEIVED_MORE_DATA_JOB = "RECEIVED_MORE_DATA_JOB";

 //user center
 export const FETCHING_USER = "FETCHING_USER";
 export const ERROR_GETTING_USER = "ERROR_GETTING_USER";
 export const RECEIVED_DATA_USER = "RECEIVED_DATA_USER";
 export const SET_DEFAULT_USER = "SET_DEFAULT_USER";
